# Generated by Django 3.2.7 on 2021-10-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211004_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
